name: Documentation 🔎 (Sphinx and PyData)

run-name: ${{ github.actor }} - Documentation 🔎 (Sphinx and PyData)

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number }}-${{ github.event.ref }}-docs
  cancel-in-progress: true

on:
  workflow_call:
    inputs:
      sha:
        description: 'The commit SHA to build from'
        required: false
        type: string
  pull_request:
  # Add push reference, so that README.md badges confirm docs build status.
  push:

jobs:
  build_docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          ref: ${{ inputs.sha || github.sha }}


      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          pip install . --group docs

      - name: Build Sphinx html documentation
        run: |
          sphinx-build -M html ./docs ./docs/_build

      - name: Build Sphinx dirhtml documentation
        run: |
          sphinx-build -M dirhtml ./docs ./docs/_build

      - name: Build Sphinx latex documentation
        run: |
          sphinx-build -M latex ./docs ./docs/_build

      # Add commands to generate and process coverage reports using sphinx-reports or similar
      - name: Sphinx Coverage
        run: |
          sphinx-build -M coverage ./docs ./docs/_build

      - name: Get version from pyproject.toml
        id: get-version
        run: |
          echo "MODULE_VERSION=$(python -c "from importlib.metadata import version; print(version('kkcalc'))")"
          echo "MODULE_VERSION=$(python -c "from importlib.metadata import version; print(version('kkcalc'))")" >> $GITHUB_ENV

      # Upload the documentation artifacts
      - name: Upload HTML Documentation
        uses: actions/upload-artifact@v7
        with:
          name: kkcalc-${{ env.MODULE_VERSION }}-docs-html
          path: docs/_build/html/

      # - name: Upload Latex Documentation
      #   uses: actions/upload-artifact@v7
      #   with:
      #     name: latex-docs
