# This is the master workflow that runs basic workflows on push, pull.
#
name: Master 👑 Workflow
run-name: ${{ github.actor }} - Master 👑 Workflow

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number }}-${{ github.event.ref }}
  cancel-in-progress: true

on:
  push:
    # Run on all branches
  pull_request:
  workflow_dispatch:
  #   inputs:
  #     gui:
  #       description: 'Generate GUI Executable?'
  #       required: true
  #       default: true
  #       type: boolean

jobs:
  linting:
    name: Linting 📜 (NumpyDoc, Ruff & Black)
    uses: ./.github/workflows/linting.yml

  testing:
    name: Tests 🔧 (PyTest, Coveralls)
    uses: ./.github/workflows/tests.yml

  docs:
    name: Documentation 🔎 (Sphinx and PyData)
    uses: ./.github/workflows/docs.yml

  # # TODO: Can add other OS builds here as needed...
  # pyinstaller-build:
  #   if: ${{ (github.event == 'workflow_dispatch' && inputs.gui == 'true') || (github.event == 'push' && needs.branch_check.outputs.is_main == 'true') }}
  #   name: kkcalc GUI 💻 (PyInstaller Executable Build)
  #   uses: ./.github/workflows/pyinst.yml
  #   needs: [testing, branch_check]
  #   with:
  #     os: 'Windows'

  # # Add write permissions to allow semantic-versioning to create tags/releases
  # semantic-versioning-and-build:
  #   name: Python 🐍 Semantic Versioning (Write)
  #   uses: ./.github/workflows/semver.yml
  #   needs: [linting, testing, docs, pyinstaller-build, branch_check]
  #   # If pyinstaller-build is skipped, stil run:
  #   if: ${{ always() && needs.linting.result == 'success' && needs.testing.result == 'success' && needs.docs.result == 'success'}}
  #   permissions:
  #     # Enforce read-only permissions on PRs, write sem-ver runs permissions otherwise
  #     contents: write
  #     id-token: write
  #   with:
  #     # Build a GUI when pushed to the 'main' branch, or when manually triggered with GUI option enabled.
  #     gui: ${{ ((github.event == 'workflow_dispatch') && inputs.gui) || (github.event == 'push' && needs.branch_check.outputs.is_main == 'true') }}
