# This workflow is the master workflow that runs all other workflows in the correct order, particularly for generating releases.
#
name: Master 👑 Workflow
run-name: ${{ github.actor }} - Master 👑 Workflow

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number }}-${{ github.event.ref }}
  cancel-in-progress: true

on:
  push:
  pull_request:

jobs:
  linting:
    name: Linting 📜 (NumpyDoc, Ruff & Black)
    uses: ./.github/workflows/linting.yml

  testing:
    name: Tests 🔧 (PyTest, Coveralls)
    uses: ./.github/workflows/tests.yml

  docs:
    name: Documentation 🔎 (Sphinx and PyData)
    uses: ./.github/workflows/docs.yml

  # TODO: Can add other OS builds here as needed...
  pyinstaller-build:
    name: kkcalc GUI 💻 (PyInstaller Executable Build)
    uses: ./.github/workflows/pyinst.yml
    needs: [testing]
    with:
      os: 'Windows'

  # Add write permissions to allow semantic-versioning to create tags/releases
  semantic-versioning-and-build:
    name: Python 🐍 Semantic Versioning
    uses: ./.github/workflows/semver.yml
    needs: [linting, testing, docs, pyinstaller-build]
    permissions:
      contents: write
      id-token: write
