# This workflow is the master workflow that runs all other workflows in the correct order, particularly for generating releases.
#
name: Release ⤴️ Workflow
run-name: ${{ github.actor }} - Release ⤴️ Workflow

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number }}-${{ github.event.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
    inputs:
      gui:
        description: 'Generate GUI Executable?'
        required: true
        default: true
        type: boolean
      noop:
        description: 'No operation mode to observe python-semantic-release output.'
        required: false
        type: boolean
        default: false
      prerelease:
        description: 'Run as a prerelease?'
        required: true
        type: boolean
        default: true
      prerelease_token:
        description: 'Token for prerelease'
        required: false
        type: choice
        options:
          - alpha
          - beta
          - rc
        default: 'beta'

jobs:
  display_inputs:
    name: Display Workflow Inputs
    runs-on: ubuntu-latest
    steps:
      - name: Display inputs for debugging
        run: |
          echo "GUI Executable: ${{ inputs.gui }}"
          echo "No-op Mode: ${{ inputs.noop }}"
          echo "Prerelease: ${{ inputs.prerelease }}"
          echo "Prerelease Token: ${{ inputs.prerelease_token }}"

  # # Check if we are on the 'main' branch or release branches:
  # branch_check:
  #   name: Branch Check 🔍
  #   runs-on: ubuntu-latest
  #   outputs:
  #     is_main: ${{ steps.check.outputs.is_main }}
  #   steps:
  #     - id: check
  #     # Check if the branch is 'main' or starts with 'releases/', and set and report the output accordingly
  #       run: |
  #         if [[ "${GITHUB_REF##*/}" == "main" || "${GITHUB_REF##*/}" == "v2" || "${GITHUB_REF##*/}" == "master" || "${GITHUB_REF##*/}" == releases/* ]]; then
  #           echo "is_main=true" >> "$GITHUB_OUTPUT"
  #           echo "Branch is_main: true"
  #         else
  #           echo "is_main=false" >> "$GITHUB_OUTPUT"
  #           echo "Branch is_main: false"
  #         fi

  linting:
    name: Linting 📜 (NumpyDoc, Ruff & Black)
    uses: ./.github/workflows/linting.yml

  testing:
    name: Tests 🔧 (PyTest, Coveralls)
    uses: ./.github/workflows/tests.yml

  docs:
    name: Documentation 🔎 (Sphinx and PyData)
    uses: ./.github/workflows/docs.yml

  # # TODO: Can add other OS builds here as needed...
  pyinstaller-build-windows:
    if: ${{ inputs.gui == 'true' }}
    name: kkcalc GUI 💻 (PyInstaller Executable Build)
    uses: ./.github/workflows/pyinst.yml
    needs: [testing]
    with:
      os: 'Windows'

  pyinstaller-build-macos:
    if: ${{ inputs.gui == 'true' }}
    name: kkcalc GUI 💻 (PyInstaller Executable Build)
    uses: ./.github/workflows/pyinst.yml
    needs: [testing]
    with:
      os: 'MacOS'

  generate-gui-artifacts-var:
    name: Generate GUI Artifacts Variable
    needs: [pyinstaller-build-windows, pyinstaller-build-macos]
    runs-on: ubuntu-latest
    outputs:
      gui_artifacts: ${{ steps.set_gui_artifacts.outputs.gui_artifacts }}
    steps:
      # Conditionally add each completed OS with a comma separator.
      - id: set_gui_artifacts
        run: |
          GUI_ARTIFACTS=""
          if [[ "${{ needs.pyinstaller-build-windows.result }}" == "success" ]]; then
            GUI_ARTIFACTS="${{ needs.pyinstaller-build-windows.outputs.NAME }}"
          fi
          if [[ "${{ needs.pyinstaller-build-macos.result }}" == "success" ]]; then
            if [[ -n "$GUI_ARTIFACTS" ]]; then
              GUI_ARTIFACTS="$GUI_ARTIFACTS,${{ needs.pyinstaller-build-macos.outputs.NAME }}"
            else
              GUI_ARTIFACTS="${{ needs.pyinstaller-build-macos.outputs.NAME }}"
            fi
          fi
          echo "GUI_ARTIFACTS=$GUI_ARTIFACTS" >> $GITHUB_OUTPUT
          echo "Generated GUI_ARTIFACTS variable: $GUI_ARTIFACTS"

  # pyinstaller-build-ubuntu:
  #   if: ${{ inputs.gui == 'true' }}
  #   name: kkcalc GUI 💻 (PyInstaller Executable Build)
  #   uses: ./.github/workflows/pyinst.yml
  #   needs: [testing, branch_check]
  #   with:
  #     os: 'Ubuntu'

  # Add write permissions to allow semantic-versioning to create tags/releases
  semantic-versioning-and-build:
    name: Python 🐍 Semantic Versioning (Write)
    uses: ./.github/workflows/semver.yml
    needs: [linting, testing, docs, pyinstaller-build-windows, pyinstaller-build-macos]
    # If pyinstaller-build is skipped, stil run:
    if: ${{ always() && needs.linting.result == 'success' && needs.testing.result == 'success' && needs.docs.result == 'success'}}
    permissions:
      contents: write
      id-token: write
    with:
      gui-artifacts: "${{ needs.pyinstaller-build-windows.outputs.NAME }},${{ needs.pyinstaller-build-macos.outputs.NAME }}"
      noop: ${{ inputs.noop }}
      prerelease: ${{ inputs.prerelease }}
      prerelease_token: ${{ inputs.prerelease_token }}
