# This workflow automatically releases pre-release versions,
# but only releases stable versions when triggered manually.
name: Python 🐍 Semantic Versioning
run-name: ${{ github.actor }} - Python 🐍 Semantic Versioning

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number }}-${{ github.ref_name }}-semver
  cancel-in-progress: false

on:
  workflow_call:
    inputs:
      noop:
        description: 'No operation mode to observe python-semantic-release output.'
        required: false
        type: boolean
        default: false
      prerelease:
        description: 'Run as a prerelease?'
        required: true
        type: boolean
        default: false
      prerelease_token:
        description: 'Token for prerelease'
        type: string
        required: false
      gui-artifacts:
        description: 'Name of GUI Artifacts from PyInstaller Build'
        required: false
        type: string

permissions:
  contents: write

jobs:
  log-inputs:
    name: Log Workflow Inputs
    runs-on: ubuntu-latest
    steps:
      - name: Log inputs for debugging
        run: |
          echo "No-op Mode: ${{ inputs.noop }}"
          echo "Prerelease: ${{ inputs.prerelease }}"
          echo "Prerelease Token: ${{ inputs.prerelease_token || 'not set' }}"
          echo "GUI Artifacts: ${{ inputs.gui-artifacts || 'not set' }}"

  semver-release:
    name: Run Python 🐍 Semantic Version to stamp distribution 📦
    # Only run this job on the master account.
    runs-on: ubuntu-latest
    # defaults: # https://github.com/actions/upload-artifact/issues/232#issuecomment-1065422577
    #   run:
    #     working-directory: ./kkcalc
    permissions:
      contents: write
    outputs:
      released: ${{ steps.is_released.outputs.released }}

    steps:
      - name: Use workflow inputs for pre-release
        shell: bash
        run: |
          echo "prerelease=${{ github.event.inputs.prerelease }}" >> $GITHUB_ENV
          echo "prerelease_token=${{ github.event.inputs.prerelease_token }}" >> $GITHUB_ENV
      - name: Display pre-release input
        shell: bash
        run: |
          echo "Python SemVer pre-release?: $prerelease"

      # Note: We checkout the repository at the branch that triggered the workflow
      # with the entire history to ensure to match PSR's release branch detection
      # and history evaluation.
      # However, we forcefully reset the branch to the workflow sha because it is
      # possible that the branch was updated while the workflow was running. This
      # prevents accidentally releasing un-evaluated changes.
      - name: Setup | Checkout Repository on Release Branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-tags: true # Ensure tags are fetched for semantic-release
          show-progress: true

          # Need to checkout a branch, so that semver can appropriately do the release.
          # Using the base_ref for pull requests, and ref for pushes/dispatches.
          ref: ${{ ( github.event_name == 'pull_request' && github.base_ref) || github.ref }}

      - name: Log | Report the conditionals for GUI tracing
        shell: bash
        run: |
          echo "Event Name: ${{ github.event_name }}"
          echo "Artifacts Input: ${{ github.event.inputs.gui-artifacts || 'not set' }}"

      - name: Separate GUI Artifacts
        # Splits GUI artifact names, also stores number of artifacts.
        shell: bash
        run: |
          if [ -n "${{ github.event.inputs.gui-artifacts }}" ]; then
            IFS=',' read -ra ARTIFACTS <<< "${{ github.event.inputs.gui-artifacts }}"
            for i in "${!ARTIFACTS[@]}"; do
              echo "ARTIFACT_$i=${ARTIFACTS[$i]}" >> $GITHUB_ENV
              echo "ARTIFACT_$i=${ARTIFACTS[$i]}"
              echo "ARTIFACT_COUNT=$((i+1))" >> $GITHUB_ENV
            done
            echo "Total GUI artifacts: $ARTIFACT_COUNT"
          else
            echo "No GUI artifacts provided."
            echo "ARTIFACT_COUNT=0" >> $GITHUB_ENV
          fi

      # Create the dist/gui/ directory if it doesn't exist
      - name: Setup | Create GUI Distribution Directory
        shell: bash
        run: |
          if [ ! -d "./dist/gui" ]; then
            mkdir -p ./dist/gui
            echo "Created ./dist/gui/ directory for GUI artifacts."
          else
            echo "./dist/gui/ directory already exists."
          fi

      # Download each artifact separately in a for loop
      - name: Download GUI Artifacts
        shell: bash
        run: |
          if [ -n "${{ github.event.inputs.gui-artifacts }}" && $ARTIFACT_COUNT -gt 0 ]; then
            for i in $(seq 0 $((ARTIFACT_COUNT-1))); do
              ARTIFACT_NAME="${!ARTIFACT_$i}"
              echo "Downloading artifact: $ARTIFACT_NAME"
              gh release download "$ARTIFACT_NAME" --repo "${{ github.repository }}" --pattern "*" --dir "./dist/gui/$ARTIFACT_NAME"
            done
            echo "Contents of ./dist:"
            ls -la ./dist/gui/
          else
            echo "No GUI artifacts to download."
          fi

      - name: Action | Semantic Version Release
        id: release
        # Adjust tag with desired version if applicable.
        # https://python-semantic-release.readthedocs.io/en/stable/configuration/automatic-releases/github-actions.html
        uses: python-semantic-release/python-semantic-release@v10.5.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          git_committer_name: "github-actions"
          git_committer_email: "actions@users.noreply.github.com"
          build: true
          prerelease: ${{ (env.prerelease || 'false') == 'true' }}
          prerelease_token: ${{ env.prerelease_token || 'beta' }}
          changelog: true
          commit: ${{ env.noop != 'true' }}
          verbosity: 2
          # Do not actually perform any release actions if:
          # 1. Not the main repository owner
          # 2. This is a pull request event - the release should only occur on push to main/release branches
          # no_operation_mode: ${{ (github.repository_owner != 'xraysoftmat' && github.repository_owner != 'benajamin') || github.event_name == 'pull_request' }}
          no_operation_mode: ${{ env.noop || 'false' }}

      - name: Env | Check if released and log conditionals
        id: is_released
        run: |
          echo "Success: ${{ steps.release.outcome }} ;  ${{ steps.release.outcome == 'success' }}"
          echo "Ownership: ${{ github.repository_owner }} ; ${{ github.repository_owner == 'xraysoftmat' || github.repository_owner == 'benajamin' }}"
          echo "Released: ${{ steps.release.outputs.released }}"
          echo "Branch: ${{ github.ref }}; ${{ github.ref == 'refs/heads/main' }}"
          echo "Push: ${{ github.event_name }} ; ${{ github.event_name == 'push' }}"
          echo "released=${{ github.event_name == 'push' && steps.release.outcome && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/v2') && steps.release.outputs.released && (github.repository_owner == 'xraysoftmat' || github.repository_owner == 'benajamin') && steps.release.outcome == 'success' }}" >> "$GITHUB_OUTPUT"

      - name: Display | Release Information
        if: |
          success() && steps.is_released.outputs.released
        run: |
          echo "Process Release: ${{ steps.is_released.outputs.released }}"
          echo "Release Tag: ${{ steps.release.outputs.tag }}"
          echo "Release Version: ${{ steps.release.outputs.version }}"
          echo "Release Branch: ${{ github.ref_name }}"
          echo "Release Prerelease: ${{ env.prerelease }}"

      - name: Publish | Upload to GitHub Release Assets
        uses: python-semantic-release/publish-action@v10.5.3
        if: |
          success() && steps.is_released.outputs.released == 'true'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.release.outputs.tag }}
          no_operation_mode: ${{ env.noop || 'false' }}

      - name: Publish | Upload to GitHub Release Assets
        uses: python-semantic-release/publish-action@v10.5.3
        if: |
          success() && steps.is_released.outputs.released == 'true'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.release.outputs.tag }}
          no_operation_mode: ${{ env.noop || 'false' }}

      - name: Upload | Distribution Artifacts
        # For use in deploying to pypi
        uses: actions/upload-artifact@v4
        if: |
          success() &&
          steps.is_released.outputs.released == 'true'
        with:
          name: distribution-artifacts
          path: ./dist
          overwrite: true
          if-no-files-found: error


  pypi-deploy-kkcalc:
    # 1. Separate out the deploy step from the publish step to run each step at
    #    the least amount of token privilege
    # 2. Also, deployments can fail, and its better to have a separate job if you need to retry
    #    and it won't require reversing the release.

    name: Publish Python 🐍 distribution 📦 release to PyPI
    runs-on: ubuntu-latest
    needs: semver-release # match the job name above
    if: |
      success() &&
      needs.semver-release.outputs.released == 'true' &&
      github.event_name != 'pull_request' &&
      github.repository_owner == 'benajamin'
    defaults:
      run:
        working-directory: ./kkcalc
    # Only run this job on the master account, only publish to PyPI on tag pushes
    permissions:
      contents: read
      id-token: write

    environment:
      name: pypi
      url: https://pypi.org/p/kkcalc

    steps:
      - name: Setup | Download Build Artifacts
        uses: actions/download-artifact@v4
        id: artifact-download
        with:
          name: distribution-artifacts # Match the name used in the upload step
          path: kkcalc/dist # Match the path used in the upload step

      - name: Publish package distribution 📦 to PyPI
        if: ${{ github.repository_owner == 'benajamin'}}
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: kkcalc/dist

  pypi-deploy-kkcalc2:
    # 1. Separate out the deploy step from the publish step to run each step at
    #    the least amount of token privilege
    # 2. Also, deployments can fail, and its better to have a separate job if you need to retry
    #    and it won't require reversing the release.
    name: Publish v2 Python 🐍 distribution 📦 release to PyPI
    runs-on: ubuntu-latest
    needs: semver-release # match the job name above
    if: |
      success() &&
      needs.semver-release.outputs.released == 'true' &&
      github.event_name != 'pull_request' &&
      github.repository_owner == 'xraysoftmat'
    defaults:
      run:
        working-directory: ./kkcalc
    # Only run this job on the master account, only publish to PyPI on tag pushes
    permissions:
      contents: read
      id-token: write

    environment:
      name: pypi
      url: https://pypi.org/p/kkcalc2

    steps:
      - name: Setup | Download Build Artifacts
        uses: actions/download-artifact@v4
        id: artifact-download
        with:
          name: distribution-artifacts # Match the name used in the upload step
          path: kkcalc/dist # Match the path used in the upload step

      - name: Publish package distribution 📦 to PyPI
        if: ${{ github.repository_owner == 'xraysoftmat'}}
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: kkcalc/dist



      # This code was originally in python-semantic-release 10.2.0 but does not appear in
      # newer 10.5.2 version. This would occur before the semantic release step.
      # https://python-semantic-release.readthedocs.io/en/latest/configuration/automatic-releases/github-actions.html
      # - name: Evaluate | Verify upstream has NOT changed
      #   # Last chance to abort before causing an error as another PR/push was applied to
      #   # the upstream branch while this workflow was running. This is important
      #   # because we are committing a version change (--commit). You may omit this step
      #   # if you have 'commit: false' in your configuration.
      #   #
      #   # You may consider moving this to a repo script and call it from this step instead
      #   # of writing it in-line.
      #   shell: bash
      #   if: ${{ github.event_name != 'workflow_dispatch' }}
      #   run: |
      #     set +o pipefail

      #     UPSTREAM_BRANCH_NAME="$(git status -sb | head -n 1 | cut -d' ' -f2 | grep -E '\.{3}' | cut -d'.' -f4)"
      #     printf '%s\n' "Upstream branch name: $UPSTREAM_BRANCH_NAME"

      #     set -o pipefail

      #     if [ -z "$UPSTREAM_BRANCH_NAME" ]; then
      #         printf >&2 '%s\n' "::error::Unable to determine upstream branch name!"
      #         exit 1
      #     fi

      #     git fetch "${UPSTREAM_BRANCH_NAME%%/*}"

      #     if ! UPSTREAM_SHA="$(git rev-parse "$UPSTREAM_BRANCH_NAME")"; then
      #         printf >&2 '%s\n' "::error::Unable to determine upstream branch sha!"
      #         exit 1
      #     fi

      #     HEAD_SHA="$(git rev-parse HEAD)"

      #     if [ "$HEAD_SHA" != "$UPSTREAM_SHA" ]; then
      #         printf >&2 '%s\n' "[HEAD SHA] $HEAD_SHA != $UPSTREAM_SHA [UPSTREAM SHA]"
      #         printf >&2 '%s\n' "::error::Upstream has changed, aborting release..."
      #         exit 1
      #     fi

      #     printf '%s\n' "Verified upstream branch has not changed, continuing with release..."

      # # - name: Delete Previous | Distribution Artifacts
      # #   uses: actions/delete-artifact@v4 ???
      # #   with:
      # #     name: distribution-artifacts
      # #     path: dist
